apps/scoreboard/urls.py
from django.urls import path
from scoreboard.views import ScoreboardView

urlpatterns = [
    path('', ScoreboardView.as_view(), name='scoreboard'),
]

temp/urls.py
from django.conf.urls import include, url
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from users.views import PrivacyPolicyView


urlpatterns = [
    # Main page
    path('', include('main.urls')),
    
    # Team Players
    path('squad/', include('squad.urls')),

    # Scoreboard and matches
    path('scoreboard/', include('scoreboard.urls')),

    # Blog
    path('blog/', include('blog.urls')),

    # Forecasts
    path('forecasts/', include('forecasts.urls')),

    # Authentication
    path('auth/', include('users.urls')),
    path('account/', include('users.account_urls')),

    # privacy policy
    path('privacy/', PrivacyPolicyView.as_view(), name='privacy'),

    # CKEditor
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    # Telegram
    path('telegram/', include('telega.urls')),
    
    # backups
    path('admin/', include('smuggler.urls')),  # before admin url patterns!
    # enable the admin interface
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/scoreboard/models.py
import re

from django.db import models, transaction
from django.utils import timezone


class Team(models.Model):
    PLACE_CHOICES = zip(range(1, 100), range(1, 100)) # 1-99

    name = models.CharField(max_length=100, null=False, blank=False)
    logo_url = models.CharField(max_length=300)
    
    class Meta:
        ordering = ['id']

    def save(self, *args, **kwargs):
        self.name = self.name.lower()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    @property
    def alias(self):
        """
        Return team name alias:
        1) strip everything except name inside quotes
        2) remove fc start
        3) abbreviation - if more than 2 words OR
        """
        name = self.name
        
        if '"' in name:
            quoted = re.compile('"[^"]*"')
            name = quoted.findall(name)[0][1:-1]
        if name.lower().startswith(('fc', 'фк')):
            name = name[2:]
        if name.lower().endswith('club'):
            name = name[:-4]
        words = name.split()
        if len(words) >= 3:
            name = ''.join([word[0] for word in words])
        return name


class League(models.Model):
    name = models.CharField(max_length=64)
    years = models.CharField(max_length=9, null=False, blank=False)
    active = models.BooleanField(default=True)
    rounds = models.PositiveIntegerField(default=2)

    class Meta:
        unique_together = (('name', 'years'),)

    def __str__(self):
        return f'{self.name} {self.years}'


class TeamInfo(models.Model):
    team = models.ForeignKey(
        Team, 
        on_delete=models.CASCADE, 
        blank=False, 
        null=False,
        related_name='participates'
    )
    league = models.ForeignKey(
        League,
        on_delete=models.CASCADE, 
        blank=False, 
        null=False, 
        related_name='teams'
    )

    PLACE_CHOICES = zip(range(1, 100), range(1, 100))  # 1-99
    MEDAL_CHOICES = (
        (1, 'Gold'),
        (2, 'Silver'),
        (3, 'Bronze'),
    )

    place = models.PositiveIntegerField(choices=PLACE_CHOICES, null=False,
                                        blank=False, default=0)
    games = models.PositiveIntegerField(null=False, blank=False, default=0)
    wins = models.PositiveIntegerField(null=False, blank=False, default=0)
    draws = models.PositiveIntegerField(null=False, blank=False, default=0)
    losses = models.PositiveIntegerField(null=False, blank=False, default=0)
    goals_scored = models.PositiveIntegerField(null=False, blank=False, default=0)
    goals_conceded = models.PositiveIntegerField(null=False, blank=False, default=0)
    points = models.PositiveIntegerField(null=False, blank=False, default=0)
    medal = models.PositiveIntegerField(choices=MEDAL_CHOICES, null=True, blank=True)
    abandoned = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.team} [{self.league} #{self.place}]'.upper()


class MatchManager(models.Manager):
    @transaction.atomic
    def update_matches(self):
        self.model.objects.update(next=None, prev=None)
        future_matches = self.model.objects.filter(date__gte=timezone.localtime(timezone.now()))
        tba_matches = self.model.objects.filter(date__isnull=True)
        next_match = None
        if future_matches.exists():
            next_match = future_matches.earliest('date')
        elif tba_matches.exists():
            next_match = tba_matches.earliest('id')

        prev_matches = self.model.objects.filter(
            date__lt=timezone.localtime(timezone.now()))
        prev_match = None
        if prev_matches.exists():
            prev_match = prev_matches.latest('date')
        if next_match:
            next_match.next = True
            next_match.save()
        if prev_match:
            prev_match.prev = True
            prev_match.save()


class Match(models.Model):
    home = models.ForeignKey(
        Team, 
        on_delete=models.CASCADE, 
        blank=False, 
        null=False,
        related_name='home_matches'
    )
    guest = models.ForeignKey(
        Team, 
        on_delete=models.CASCADE, 
        blank=False, 
        null=False,
        related_name='away_matches'
    )
    score = models.CharField(max_length=6, default='-')
    link = models.CharField(max_length=200, blank=True, null=True)
    date = models.DateTimeField(null=True, blank=True)
    league = models.CharField(max_length=20, default='HFL')
    next = models.BooleanField(default=None, unique=True, null=True)
    prev = models.BooleanField(default=None, unique=True, null=True)

    objects = MatchManager()

    def __str__(self):
        return f'{self.home.name} {self.score} {self.guest.name}' 

    def save(self, *args, **kwargs):
        # make bools next & prev True only for one Match
        if self.next is False:
            self.next = None
        if self.prev is False:
            self.prev = None
        super().save(*args, **kwargs)

apps/scoreboard/views.py
from django.views.generic import TemplateView

from scoreboard.services import get_latest_league_context


class ScoreboardView(TemplateView):
    template_name = "scoreboard/scoreboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # self.refresh_scoreboard()
        context['scoreboard'] = get_latest_league_context()
        return context

templates/scoreboard/birthdays.html
{% load static %}
{% if birthdays %}
<div class="birthdays">
    {% for player in birthdays %}
        <div class="birthday shadow" style="background-image: url({% static 'img/triangles.png' %});">
            <div class="photo" style="background-image: url({{ player.photo.url }});">

            </div>
            <div class="bd-info">
                <h1>{{ player.full_name }}</h1>
                <h2>{{ player.years }} років</h2>
                <h3>{{ player.date_of_birth|date:"d.m.Y" }}</h3>
            </div>
        </div>
    {% endfor %}
</div>
{% endif %}

templates/scoreboard/matches.html
{% load static %}
<div class="sidebar">
    {% include 'scoreboard/birthdays.html' %}
    {% if next_match %}
        <div class="match next-match shadow">
            <p class="type">НАСТУПНИЙ МАТЧ</p>
            <div class="info">
                <p class="date">
                    {% if next_match.date %}
                        <p>{{ next_match.date|date:"d/m/Y H:i" }}</p>
                        <div id="countdown" class="countdown simple-bar" data-Date="{{ next_match.date|date:'c' }}" data-endText="" data-zeroPad='{"Days": "false"}'>
                            (days) дні, (hours):(minutes):(seconds)
                        </div>
                    {% else %}
                        TBA
                    {% endif %}
                </p>
                <p class="competition"><b>{{ next_match.league }}</b></p>
            </div>
            <div class="sides">
                <div class="team">
                    <img src="{{ next_match.home.logo_url }}">
                    <p class="name">{{ next_match.home.alias }}</p>
                </div>
                <div class="score time">
                    <p>-</p>
                </div>
                <div class="team">
                    <img src="{{ next_match.guest.logo_url }}">
                    <p class="name">{{ next_match.guest.alias }}</p>
                </div>
            </div>
            <a href="{{ next_match.link }}" target="_blank">
                <div class="link">
                    <p>ПРОТОКОЛ</p>
                </div>
            </a>
        </div>
    {% else %}
        
    {% endif %}

    {% if prev_match %}
        <div class="match prev-match shadow">
            <p class="type">ОСТАННІЙ РЕЗУЛЬТАТ</p>
            <div class="info">
                <p class="date" data-date="{{ prev_match.date }}">{{ prev_match.date|date:"d/m/Y" }}</p>
                <p class="competition"><b>{{ prev_match.league }}</b></p>
            </div>
            <div class="sides">
                <div class="team">
                    <img src="{{ prev_match.home.logo_url }}">
                    <p class="name">{{ prev_match.home.alias }}</p>
                </div>
                <div class="score">
                    <p>{{ prev_match.score }}</p>
                </div>
                <div class="team">
                    <img src="{{ prev_match.guest.logo_url }}">
                    <p class="name">{{ prev_match.guest.alias }}</p>
                </div>
            </div>
            <a href="{{ prev_match.link }}" target="_blank">
                <div class="link">
                    <p>ПРОТОКОЛ</p>
                </div>
            </a>
        </div>
    {% else %}
        
    {% endif %}
</div>

templates/scoreboard/scoreboard.html
{% extends 'base.html' %}

{% block title %}Scoreboard{% endblock %}

{% block content %}
<div class="container mtb20">
    {% include 'scoreboard/table.html' %}
</div>
{% endblock %}

templates/scoreboard/table.html
{% load static %}
{% load config %}
<div class="scoreboard shadow">
    {% if user.is_staff %}
        <form action="{% url 'index' %}" id="refresh-scoreboard" method="POST">
            <input type="submit" value="ОНОВИТИ">
        </form>
    {% endif %}
    <div class="stamp">
        Останнє оновлення: {{ 'scoreboard.updated_at'|get_config }}
    </div>
    <div class="heading">
        <p class="place">#</p>
        <p class="team-name">Команда</p>
        <p class="games">І</p>
        <p class="wins">В</p>
        <p class="draws">Н</p>
        <p class="losses">П</p>
        <p class="goals">МЗ - МП</p>
        <p class="points">О</p>
    </div>
    <div class="table">
        {% for teaminfo in scoreboard %}
        <div class="team {% if teaminfo.team.name.lower == 'темп' %}dymer{% endif %}">
            <p class="place">{{ teaminfo.place }}</p>
            <div class="team-name">
                <img src="{{ teaminfo.team.logo_url }}" >
                <p>{{ teaminfo.team.alias }}</p>
                {% if teaminfo.medal %}
                    <div class="medal {{ teaminfo.get_medal_display|lower }}">
                        {{ teaminfo.medal }}
                    </div>
                {% endif %}
            </div>
            <p class="games">{{ teaminfo.games }}</p>
            <p class="wins">{{ teaminfo.wins }}</p>
            <p class="draws">{{ teaminfo.draws }}</p>
            <p class="losses">{{ teaminfo.losses }}</p>
            <p class="goals">{{ teaminfo.goals_scored }} - {{ teaminfo.goals_conceded }}</p>
            <p class="points"><b>{{ teaminfo.points }}</b></p>
        </div>
        {% endfor %}
    </div>
</div>