apps/squad/urls.py
from django.urls import path
from squad.views import (
    PlayerListView, 
    PlayerDetailView, 
    LineupGeneratorView, 
    LineupDownloadView,
    SquadDetailView
)

urlpatterns = [
    path('', PlayerListView.as_view(), name='player-list'),
    path('lineup/', LineupGeneratorView.as_view(), name='lineup'),
    path('lineup/download/', LineupDownloadView.as_view(), name='lineup-download'),
    path('lineup/<slug:slug>/', SquadDetailView.as_view(), name='lineup-detail'),
    path('<slug:name_slug>/', PlayerDetailView.as_view(), name='player-detail'),
]

temp/urls.py
from django.conf.urls import include, url
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from users.views import PrivacyPolicyView


urlpatterns = [
    # Main page
    path('', include('main.urls')),
    
    # Team Players
    path('squad/', include('squad.urls')),

    # Scoreboard and matches
    path('scoreboard/', include('scoreboard.urls')),

    # Blog
    path('blog/', include('blog.urls')),

    # Forecasts
    path('forecasts/', include('forecasts.urls')),

    # Authentication
    path('auth/', include('users.urls')),
    path('account/', include('users.account_urls')),

    # privacy policy
    path('privacy/', PrivacyPolicyView.as_view(), name='privacy'),

    # CKEditor
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    # Telegram
    path('telegram/', include('telega.urls')),
    
    # backups
    path('admin/', include('smuggler.urls')),  # before admin url patterns!
    # enable the admin interface
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/squad/models.py
from datetime import datetime, date

from django.db import models
from django.utils.crypto import get_random_string
from django.contrib.auth.models import User

from slugify import slugify
from django_countries.fields import CountryField



class Player(models.Model):
 
    NUMBER_CHOICES = zip(range(1, 100), range(1, 100)) # 1-99

    GK = 1
    DF = 2
    MF = 3
    ST = 4
    MG = 5
    POSITION_CHOICES = (
        (GK, 'Воротар'),
        (DF, 'Захисник'),
        (MF, 'Півзахисник'),
        (ST, 'Нападник'),
        (MG, 'Тренер')
    )

    first_name = models.CharField(max_length=100, null=False, blank=False)
    middle_name = models.CharField(max_length=100, null=True, blank=True)
    last_name = models.CharField(max_length=100, null=False, blank=False)
    number = models.PositiveIntegerField(choices=NUMBER_CHOICES, db_index=True, null=True, blank=True, unique=True)
    position = models.PositiveIntegerField(choices=POSITION_CHOICES, null=False, blank=False)
    date_of_birth = models.DateField(null=False, blank=False)
    photo = models.ImageField(upload_to='squad/')
    captain = models.BooleanField(default=None, unique=True, null=True)
    nationality = CountryField()
    name_slug = models.SlugField(max_length=200, unique=True, null=True)
    legend = models.BooleanField(default=False, null=False, blank=False)

    def __str__(self):
        return f'{self.number}. {self.first_name} {self.last_name}'

    def save(self, *args, **kwargs):
        # make slug from first and last names
        self.name_slug = '-'.join((slugify(self.first_name), slugify(self.last_name)))
        if str(self.number).isdigit():
            self.name_slug += f'-{self.number}'
        else:
            self.name_slug += f'-{self.pk}'

        # make captain bool True only for one Player
        if self.captain is False:
            self.captain = None
        super().save(*args, **kwargs)

    @property
    def years(self):
        today = date.today()
        return today.year - self.date_of_birth.year - ((today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day)) 

    @property
    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        ordering = ['number']

    @property
    def position_ukranian(self):
        positions = {
            'goalkeeper': 'Вр',
            'defender': 'Зх',
            'midfielder': 'Цп',
            'striker': 'Нп',
            'manager': 'Тр'
        }
        return positions[self.position]


class Squad(models.Model):
    pitch_html = models.TextField()
    slug = models.SlugField(max_length=30, blank=True)
    author = models.ForeignKey(
        User, 
        on_delete=models.SET_NULL, 
        blank=False, 
        null=True
    )
    created_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        try:
            self.slug = get_random_string(30)
            super().save(*args, **kwargs)
        except IntegrityError:
            self.save(*args, **kwargs)

apps/squad/views.py
from django.utils import timezone
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseForbidden, FileResponse, HttpResponse
from django.db import transaction

from squad.models import Player, Squad

class PlayerListView(ListView):
    model = Player
    ordering = ['position', 'number', ]


class PlayerDetailView(DetailView):
    model = Player
    slug_field = 'name_slug'
    slug_url_kwarg = 'name_slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['extra'] = 'test'
        return context


class LineupGeneratorView(ListView):
    # model = Player
    ordering = ['number']
    template_name = 'squad/lineup-generator.html'

    # only players needed for starting 11
    queryset = Player.objects.exclude(position=Player.MG)


@method_decorator(csrf_exempt, name='dispatch')
class LineupDownloadView(View):

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return HttpResponseForbidden()
        table = request.POST.get('table_html')
        
        return HttpResponse('test')


class SquadDetailView(DetailView):
    model = Squad
    template_name = "squad/lineup.html"
    

templates/squad/lineup-generator.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Створити схему{% endblock %}

{% block head %}
<!-- Selectric -->
<link rel="stylesheet" href="{% static 'css/selectric.css' %}">
<script src="{% static 'js/jquery.selectric.js' %}"></script>

<script src="{% static 'js/lineup.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/lineup.css' %}">
{% endblock%}

{% block content %}
    <div class="container">
        <select name="players" id="players">
                <option value="" disabled selected>Гравець</option>
            {% for player in object_list %}
                <option value="{% if player.number %}{{ player.number }}{% endif %}" data-surname="{{ player.last_name }}">({{ player.number }}) {{ player.last_name }}</option>
            {% endfor %}
        </select>
        
        <div id="scheme">
            <h2>Схема:</h2>
            <label><input type="radio" name="scheme" value="s442" checked>4 - 4 - 2</label>
            <label><input type="radio" name="scheme" value="s451">4 - 5 - 1</label>
            <label><input type="radio" name="scheme" value="s433">4 - 3 - 3</label>
        </div>

        <div class="field s442">
            <img src="{% static 'img/pitch.svg' %}" class="pitch stripes">
            
            <!-- TODO -->
            <!-- <form action="{% url 'lineup-download' %}" id="download-lineup" class="btn" method="POST">
                <input type="submit" value="ЗАВАНТАЖИТИ">
            </form> -->
            

            <!-- 11 players -->

            <div class="player gk">
                <div class="wrapper">
                    <h2>23</h2>
                    <h3>Батеха</h3>
                </div>
            </div>

            <div class="player">
                <div class="wrapper">
                    <h2>2</h2>
                    <h3></h3>
                </div>
            </div>

            <div class="player">
                <div class="wrapper">
                    <h2>3</h2>
                    <h3></h3>
                </div>
            </div>

            <div class="player">
                <div class="wrapper">
                    <h2>4</h2>
                    <h3></h3>
                </div>
            </div>

            <div class="player">
                <div class="wrapper">
                    <h2>5</h2>
                    <h3></h3>
                </div>
            </div>

            <div class="player">
                <div class="wrapper">
                    <h2>6</h2>
                    <h3></h3>
                </div>
            </div>

            <div class="player">
                <div class="wrapper">
                    <h2>7</h2>
                    <h3></h3>
                </div>
            </div>

            <div class="player">
                <div class="wrapper">
                    <h2>8</h2>
                    <h3></h3>
                </div>
            </div>

            <div class="player">
                <div class="wrapper">
                    <h2>9</h2>
                    <h3></h3>
                </div>
            </div>

            <div class="player">
                <div class="wrapper">
                    <h2>10</h2>
                    <h3></h3>
                </div>
            </div>

            <div class="player">
                <div class="wrapper">
                    <h2>11</h2>
                    <h3></h3>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/squad/lineup.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Стартовий склад{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/lineup.css' %}">
{% endblock%}

{% block content %}
    <div class="container">
        {% autoescape off %}
            {{ object.pitch_html }}
        {% endautoescape %}
    </div>
{% endblock %}

templates/squad/player_detail.html
{% extends 'base.html' %}

{% block title %}{{object.first_name}} {{object.last_name}}{% endblock %}

{% block content %}
    <div class="container title">
        <h1>{{object.full_name}}  #{{object.number}}</h1>
    </div>
    <div class="container">
        <img src="{{object.photo.url}}"><br>
        Вік: {{object.years}} років ({{object.date_of_birth}}) <br>
        Амплуа: {{object.get_position_display}}<br>
        
    </div>
{% endblock %}

templates/squad/player_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Гравці{% endblock %}

{% block content %}
    
    <div class="container">
        {% if user.is_staff %}
            <div id="create-squad">
                <a href="{% url 'lineup' %}" class="link-btn">
                    СТВОРИТИ СКЛАД
                </a>
            </div>
        {% endif %}
    </div>
    {% regroup object_list by get_position_display as positions_list %}
        {% for position in positions_list %}
            <div class="container title">
                <h1>{{ position.grouper }}{% if position.grouper == 'Воротар' %}і{% else %}и{% endif %}</h1>
            </div>
            <div class="container mtb20 player-container">
                {% for player in position.list %}
                    <a href="{% url 'player-detail' name_slug=player.name_slug %}">
                        {% if player.legend %}
                            <img src="{% static 'img/crown.svg' %}" class="crown">
                        {% endif %}
                        {% if player.captain%}
                            <img src="https://static.thenounproject.com/png/1963245-200.png" class="crown">
                        {% endif %}
                        <div class="card shadow {% if player.legend %}legend{% endif %}">
                            <div class="photo" style="background-image: url({{ player.photo.url }});">
                                <div class="nationality" style="background-image: url(https://www.countryflags.io/{{player.nationality.code}}/flat/64.png);">
                                </div>
                            </div>
                            <div class="name">
                                <h2>
                                    {{ player.first_name }} <br>{{ player.last_name }}
                                </h2>
                            </div>
                            {% if player.number %}
                                <p class="number">
                                    {{ player.number }}
                                </p>
                            {% endif %}
                        </div>
                    </a>
                {% endfor %}
            </div>
        {% endfor %}
{% endblock %}